=== davidteles/POO/project/simulation.dtd
<!ELEMENT simulation (grid, initialpoint, finalpoint, specialcostzones?, obstacles?, events)>
<!ELEMENT grid EMPTY>
<!ELEMENT inicialpoint EMPTY>
<!ELEMENT finalpoint EMPTY>
<!ELEMENT specialcostzones (zone+)>
<!ELEMENT zone ANY>
<!ELEMENT obstacles (obstacle+)>
<!ELEMENT obstacle EMPTY>
<!ELEMENT events (death, reproduction, move)>
<!ELEMENT death EMPTY>
<!ELEMENT reproduction EMPTY>
<!ELEMENT move EMPTY>

<!ATTLIST simulation finalinst CDATA #REQUIRED>
<!ATTLIST simulation initpop CDATA #REQUIRED>
<!ATTLIST simulation maxpop CDATA #REQUIRED>
<!ATTLIST simulation comfortsens CDATA #REQUIRED>
<!ATTLIST grid colsnb CDATA #REQUIRED>
<!ATTLIST grid rowsnb CDATA #REQUIRED>
<!ATTLIST initialpoint xinitial CDATA #REQUIRED>
<!ATTLIST initialpoint yinitial CDATA #REQUIRED>
<!ATTLIST finalpoint xfinal CDATA #REQUIRED>
<!ATTLIST finalpoint yfinal CDATA #REQUIRED>
<!ATTLIST zone xinitial CDATA #REQUIRED>
<!ATTLIST zone yinitial CDATA #REQUIRED>
<!ATTLIST zone xfinal CDATA #REQUIRED>
<!ATTLIST zone yfinal CDATA #REQUIRED>
<!ATTLIST obstacles num CDATA #REQUIRED>
<!ATTLIST obstacle xpos CDATA #REQUIRED>
<!ATTLIST obstacle ypos CDATA #REQUIRED>
<!ATTLIST death param CDATA #REQUIRED>
<!ATTLIST reproduction param CDATA #REQUIRED>
<!ATTLIST move param CDATA #REQUIRED>

=== davidteles/POO/project/data4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE simulation SYSTEM "simulation.dtd">
<simulation finalinst="100" initpop="10" maxpop="500" comfortsens="3"> 
   <grid colsnb="10" rowsnb="10"></grid> 
   <initialpoint xinitial="1" yinitial="1"/>
   <finalpoint xfinal="9" yfinal="9"/>
   <specialcostzones>
      <zone xinitial="2" yinitial="2" xfinal="3" yfinal="3">4</zone>
   </specialcostzones>
   <obstacles num="10">
      <obstacle xpos="4" ypos="1"/>
      <obstacle xpos="4" ypos="2"/>
      <obstacle xpos="4" ypos="3"/>
      <obstacle xpos="4" ypos="4"/>
      <obstacle xpos="1" ypos="4"/>
      <obstacle xpos="2" ypos="4"/>
      <obstacle xpos="2" ypos="5"/>
      <obstacle xpos="2" ypos="6"/>
      <obstacle xpos="3" ypos="6"/>
      <obstacle xpos="4" ypos="6"/>
   </obstacles>
   <events>
      <death param="10"/>
      <reproduction param="1"/>
      <move param="1"/>
   </events>
</simulation>
